---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-1
  labels:
    app: nginx-deployment-1
spec:
  ports:
  - name: client
    port: 9443
    targetPort: 80
    protocol: TCP
  type: LoadBalancer    
  selector:
    app: nginx-deployment-1

