kind: PersistentVolume
apiVersion: v1
metadata:
  name: task1-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/log/nginx"

